const assert=require('node:assert/strict');
const {changes}=require('../src/city-signals');
const before={key:'outer',seed:'test',tick:1,people:[{id:'a',x:0,y:0,awakened:false,investigating:false}],repairs:[{id:'r',x:0,y:0,actions:2}],programs:[{id:'p',x:1,y:1,actions:0,quarantined:false}],anomalies:[]};
const after=structuredClone(before);after.tick=2;after.people[0].investigating=true;after.repairs[0].actions=5;after.programs[0].quarantined=true;after.anomalies.push({id:'g',x:2,y:3});
const serialized=JSON.stringify([before,after]);
assert.deepEqual(changes(before,after).map(s=>s.kind),['inquiry','repair','quarantine','glitch']);
assert.equal(changes(before,after)[1].label,'+3 REPAIR ACTIONS');
assert.equal(JSON.stringify([before,after]),serialized);
assert.deepEqual(changes(after,after),[]);
for(const patch of [{tick:0},{key:'nested'},{seed:'new'}])assert.deepEqual(changes(before,{...after,...patch}),[]);
assert.deepEqual(changes(null,after),[]);
after.people[0].awakened=true;assert.equal(changes(before,after)[0].kind,'break');
after.repairs[0].actions=1;assert(!changes(before,after).some(s=>s.kind==='repair'));
// Same-tick intervention is visible; a new entity is not evidence of prior activity.
assert(changes(before,{...after,tick:1}).some(s=>s.kind==='glitch'));
after.programs.push({id:'new',x:2,y:2,actions:100});assert(!changes(before,after).some(s=>s.id==='new'));
const result=changes(before,after);result[0].x=100;assert.equal(after.people[0].x,0);
console.log('City signals: PASS (observed deltas, purity, reset, rewind, same-tick intervention, no invented history)');
// Exercise the real renderer's signal lifetime without a browser or a simulated engine.
const vm=require('node:vm'),fs=require('node:fs');let now=100;
const context={window:{AnomalyGardenCityProjection:{hash:()=>1},AnomalyGardenCitySignals:{changes}},performance:{now:()=>now}};
vm.runInNewContext(fs.readFileSync(require.resolve('../src/city-renderer'),'utf8'),context);
const renderer=Object.create(context.window.AnomalyGardenCityRenderer.prototype);
Object.assign(renderer,{scene:null,signals:[],previous:new Map(),targets:new Map(),width:1000});
renderer.setScene(before);assert.equal(renderer.signals.length,0);
renderer.setScene(after);assert(renderer.signals.length>0);
const count=renderer.signals.length;renderer.setScene(after);assert.equal(renderer.signals.length,count);
now+=2500;renderer.setScene(after);assert.equal(renderer.signals.length,0);
renderer.setScene(before);assert.equal(renderer.signals.length,0);
renderer.setScene(after);renderer.setScene({...after,key:'nested'});assert.equal(renderer.signals.length,0);
console.log('City renderer signal lifecycle: PASS (deduplication, expiry, rewind, layer reset)');
